// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_FluentUI();
Q_GHS_KEEP_REFERENCE(qml_register_types_FluentUI)

class FluentUIPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    FluentUIPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_FluentUI;
        Q_UNUSED(registration)
    }
};



#include "fluentuiplugin_FluentUIPlugin.moc"
